server:
    servlet:
        contextPath: /api
    port: 8080

spring:
  http.multipart.enabled: false
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

  jpa:
    hibernate.ddl-auto: create #update - for prod
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties.hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: root
    password: root